addSbtPlugin("com.geirsson"      % "sbt-scalafmt"        % "0.4.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"             % "0.8.5")
addSbtPlugin("com.typesafe.sbt"  % "sbt-multi-jvm"       % "0.3.11")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.1.4")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "1.6.0")
addSbtPlugin("io.spray"          % "sbt-revolver"        % "0.8.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.3.5")
