addSbtPlugin("com.danieltrinh"   % "sbt-scalariform" % "1.3.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"         % "0.8.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-multi-jvm"   % "0.3.10-8ea98a7927ea5a6ef05b8adea0e85deceacff85f")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "1.5.0")
addSbtPlugin("io.spray"          % "sbt-revolver"    % "0.7.2")
